// Generated by dts-bundle-generator v6.11.0

import { Renderer } from '@pixi/core';
import { Graphics } from '@pixi/graphics';
import { InteractionEvent } from '@pixi/interaction';
import { Text } from '@pixi/text';

export declare class HitAreaFrames extends Graphics {
	initialized: boolean;
	texts: Text[];
	strokeWidth: number;
	normalColor: number;
	activeColor: number;
	constructor();
	init(): void;
	onPointerMove(e: InteractionEvent): void;
	/** @override */
	protected _render(renderer: Renderer): void;
}

export {};
